package:
  name: ck
  version: 1.2.0605

source:
  path: ..

build:
  number: 0
  entry_points:
    - ck = ck.kernel:main

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - ck.kernel
  commands:
    - ck
